# Generated by Django 3.0.7 on 2020-06-13 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(help_text='Conteúdo que será publicado.', verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'página',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(blank=True, help_text='O subtítulo da página para os mecanismos de busca.', max_length=255, verbose_name='Subtítulo')),
                ('body', wagtail.core.fields.RichTextField(verbose_name='Conteúdo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de publicação que será exibida no site.', verbose_name='Data de publicação')),
                ('image', models.ForeignKey(help_text='Imagem que servirá de capa para o post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Imagem de destaque')),
            ],
            options={
                'verbose_name': 'post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndexPageFeaturedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('index_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='blog.IndexPage')),
                ('post_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.PostPage', verbose_name='Post')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
